import { colors } from '../utils/styles';

export const themeCalendar = {
  backgroundColor: colors.primaryColor,
  calendarBackground: colors.primaryColor,
  textSectionTitleColor: colors.secondaryColor,
  textSectionTitleDisabledColor: '#d9e1e8',
  selectedDayBackgroundColor: colors.orange,
  selectedDayTextColor: colors.primaryColor,
  todayTextColor: colors.blue,
  dayTextColor: '#d9e1e8',
  textDisabledColor: '#2d4150',
  dotColor: '#00adf5',
  selectedDotColor: '#ffffff',
  arrowColor: colors.orange,
  disabledArrowColor: '#2d4150',
  monthTextColor: colors.orange,
  indicatorColor: 'blue',
  textDayFontFamily: 'Anton-Regular',
  textMonthFontFamily: 'Anton-Regular',
  textDayHeaderFontFamily: 'Anton-Regular',
  textDayFontWeight: '300',
  textMonthFontWeight: 'bold',
  textDayHeaderFontWeight: '300',
  textDayFontSize: 16,
  textMonthFontSize: 16,
  textDayHeaderFontSize: 14,
};

export const localesPt = {
  monthNames: [
    'Janeiro',
    'Fevereiro',
    'Março',
    'Abril',
    'Maio',
    'Junho',
    'Julho',
    'Agosto',
    'Setembro',
    'Outubro',
    'Novembro',
    'Dezembro',
  ],
  monthNamesShort: [
    'Jan',
    'Fev',
    'Mar',
    'Abr',
    'Mai',
    'Jun',
    'Jul',
    'Ago',
    'Set',
    'Out',
    'Nov',
    'Dez',
  ],
  dayNames: [
    'Domingo',
    'Segunda',
    'Terça',
    'Quarta',
    'Quinta',
    'Sexta',
    'Sábado',
  ],
  dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
  today: "Hoje'Hoje",
};
